[[pages]]
path = "Inicio.py"
name = "Pagina Inicial"
icon = "ğŸ "

[[pages]]
path = "pages/CGR.py"
name = "Cadastro Geral de RecomendaÃ§Ãµes"
icon = "ğŸ“"

[[pages]]
path = "pages/Cancelamentos.py"
name = "Cancelamento de Itens"
icon = "âŒ"